[package]
name = "ja-resume"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Nikudanngo"]
license = "MIT"
description = "日本でよく使われるな形式の履歴書をTypstで作成するテンプレート"
repository = "https://github.com/Nikudanngo/typst-ja-resume-template"
categories = ["cv"]
keywords = ["resume", "cv", "japanese", "japan", "履歴書", "jis"]
exclude = [
  "fonts/**",
  "image/testImage.png",
  "main.pdf",
  ".vscode/**",
]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
